### ISSUE TITLE
lineageos 14.1 bootloop d802

### ISSUE THREAD

**Issue by montvid** [blastagator/LGG2_TWRP_Kernel#1]
when one uses the lineageos 14.1 updater the phone boots into recovery but does not update. Rebooting the phone one gets back into the recovery. Can't boot into lineageos 14.1 anymore. To fix it one needs this:
Connect your device to your computer via USB and run this command as root: adb shell dd if=/dev/zero of=/dev/block/platform/msm_sdcc.1/by-name/misc count=1 bs=32
reboot, os is loading. works.
https://www.reddit.com/r/LineageOS/comments/5riech/how_fix_twrp_recovery_boot_loop_after_lineageos/?st=izzoc9gd&sh=5f22ee7e
Could it be lg g2 d802 twrp 3.0.3a issue? people upgrading to official 3.0.3 see the problem disappear but not on your build it seems.
Thanks for your support!

**Comment by blastagator** [comment]
/misc isn't mounted, that's why this happens.  Mounting /misc wipes phone if you enter recovery via key combo.  ROM needs to mount /misc as /pad, then we can mount /pad and not have the problem.  Alternatively /misc can be used with an offset.  No one really actively maintains g2 LOS repos, so without them doing one of those two things, there is nothing I can do.

**Comment by montvid** [comment]
Thanks for the reply. How to find the email of the maintainer... or someone. By the way, what rom do you use on lg g2 - or which is actively maintained?
